apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-actions-exporter
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "monitoring.fullLabels" "github-actions-exporter" | nindent 4 }}
spec:
  replicas: {{ .Values.githubActionsExporter.replicas }}
  selector:
    matchLabels:
      {{- include "monitoring.selectorLabels" "github-actions-exporter" | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "monitoring.fullLabels" "github-actions-exporter" | nindent 8 }}
    spec:
      nodeSelector: {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: github-actions-exporter
          image: {{ .Values.githubActionsExporter.image }}
          env:
            - name: GITHUB_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-actions-exporter-credentials
                  key: github-token
                  optional: true
            - name: GITHUB_WEBHOOK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-actions-exporter-credentials
                  key: github-webhook-token
                  optional: true
            - name: GITHUB_ORG
              valueFrom:
                secretKeyRef:
                  name: github-actions-exporter-credentials
                  key: github-org
                  optional: true
          ports:
            - containerPort: {{ .Values.githubActionsExporter.service.port }}
              name: metrics
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.githubActionsExporter.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: github-actions-exporter
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "monitoring.fullLabels" "github-actions-exporter" | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.githubActionsExporter.service.port }}"
spec:
  type: ClusterIP
  selector:
    {{- include "monitoring.selectorLabels" "github-actions-exporter" | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.githubActionsExporter.service.port }}
      targetPort: {{ .Values.githubActionsExporter.service.port }}
      protocol: TCP
