{{- if .Values.alloy.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: alloy-faro-ingress
  namespace: {{ .Values.namespace }}
  labels: {{- include "monitoring.fullLabels" "alloy" | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: {{ .Values.alloy.ingress.matchRule }}
      kind: Rule
      priority: 110
      services:
        - name: alloy
          port: {{ .Values.alloy.service.faroPort }}
      middlewares:
        - name: faro-stripprefix
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: faro-stripprefix
  namespace: {{ .Values.namespace }}
  labels: {{- include "monitoring.fullLabels" "alloy" | nindent 4 }}
spec:
  stripPrefix:
    prefixes:
      - /faro
{{- end }}
