apiVersion: v1
kind: Service
metadata:
  name: alloy
  namespace: {{ .Values.namespace }}
  labels: {{- include "monitoring.fullLabels" "alloy" | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "monitoring.selectorLabels" "alloy" | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.alloy.service.httpPort }}
      targetPort: {{ .Values.alloy.service.httpPort }}
      protocol: TCP
    - name: faro
      port: {{ .Values.alloy.service.faroPort }}
      targetPort: {{ .Values.alloy.service.faroPort }}
      protocol: TCP
