{{- if .Values.prometheus.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-ingress
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "monitoring.fullLabels" "prometheus" | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.adminAccess.hostname }}`) && {{ .Values.prometheus.ingress.matchRule }}
      kind: Rule
      priority: 100
      {{- if .Values.adminAccess.enabled }}
      middlewares:
        - name: admin-ip-allowlist
      {{- end }}
      services:
        - name: prometheus
          port: 9090
  tls:
    secretName: ops-tls-cert
{{- end }}
